
# 1. qemu-multi with my u-boot
# U-Boot 2017.01-00069-gbb1d1fa-dirty (Sep 26 2017 - 06:55:29 -0700) Xilinx ZynqMP ZCU102 (built from source code)
# original working : U-Boot 2017.01 (Jul 14 2017 - 08:43:06 -0700) Xilinx ZynqMP ZCU102 revB (uboot image from yocto)
# now my u-boot build works (after changing u-boot environment variables in include/configs/xilinx_zynqmp.h.
# boot to the end with login prompt! (only 4 CPUs are recognized)
sudo gdb --args /home/dkang/WORK/qemu-build-multi/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/hw.dtb -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/multi-u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt,accel=tcg -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt
#sudo gdb --args /home/dkang/git-Xilinx/qemu-build/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/hw.dtb -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=tmp/deploy/images/zcu102-zynqmp/u-boot.elf  -device loader,addr=0x4000000,file=tmp/deploy/images/zcu102-zynqmp/Image-zynqmp-zcu102-revB.dtb -device loader,addr=0x80000,file=tmp/deploy/images/zcu102-zynqmp/Image -machine arm-generic-fdt  -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt
#sudo gdb --args /home/dkang/WORK/qemu-build-multi/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/hw.dtb -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt,accel=tcg -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt

# 2. qemu-multi with my u-boot (without PMU boot)
# configs/hpsc_multi_defconfig::CONFIG_CLK_ZYNQMP=n
# login prompt is not shown. udev keeps searching for devices (only 4 CPUs are recognized)
#sudo gdb --args /home/dkang/WORK/qemu-build-multi/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/hw.dtb -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt,accel=tcg -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt

# 3. qemu-multi with my u-boot (without PMU boot)
#    without -global xlnx,zynqmp-boot.use-pmufw=true
#    qemu still waits for qemu-pmu.
#    Fails with the followiong error message:
#    initcall sequence 000000007ff8b670 failed at call 0000000008002f70 (err=-22)
#    ### ERROR ### Please RESET the board ###
#sudo gdb --args /home/dkang/WORK/qemu-build-multi/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/hw.dtb -global xlnx,zynqmp-boot.cpu-num=0 -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt,accel=tcg -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt

# 4. qemu-single with my u-boot (without PMU boot)
#    without -global xlnx,zynqmp-boot.use-pmufw=true  (with multi architecture hw.dtb) -->	still wait for qemu-pmu. the same as 3.
#    without -global xlnx,zynqmp-boot.use-pmufw=true  (with my hw-single.dtb)            -->Even ATW is not loaded. "Warning: vlan 0 is not connected to host network"
#    without -global xlnx,zynqmp-boot.use-pmufw=true  (with my DK/Single-Ref/zynqmp-qemu-arm.dtb )   -->         Even ATW is not loaded. "Warning: vlan 0 is not connected to host network"
#sudo gdb --args /home/dkang/WORK/qemu-build-single/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/Single-Ref/zynqmp-qemu-arm.dtb -global xlnx,zynqmp-boot.cpu-num=0 -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt,accel=tcg -m 4096 -machine-path /tmp/qemu -D ./apu-test.log -d int,guest_errors,in_asm,fdt

# 5. qemu-single with my u-boot (without PMU boot)
#    without -global xlnx,zynqmp-boot.use-pmufw=true  (with my DK/Single-Ref/zynqmp-qemu-arm.dtb )
#    without -global xlnx,zynqmp-boot.cpu-num=0     --> Even ATF is not loaded
#    without -machine-path 	,accl-tcg is removed --> Even ATF is not loaded
#sudo gdb --args /home/dkang/WORK/qemu-build-single/aarch64-softmmu/qemu-system-aarch64 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/Single-Ref/zynqmp-qemu-arm.dtb -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt -m 4096 -D ./apu-test.log -d int,guest_errors,in_asm,fdt

# 6. qemu-single with my u-boot (without PMU boot)
#   5+
#   add "-device loader,addr=0xfd1a0104,data=0x8000000e,data-len=4"  // this is reset CPU1, CPU2, CPU3 in xilinx_zynqmp_crf.c of qemu
#   --> now Uboot is loaded. Uboot Fails with message "initcall sequence 000000007ff8b670 failed at call 0000000008002f70 (err=-22)"
#   zynqmp_clk_get_peripheral_rate: read (0xff5e0074), value (0x1000500)
#   zynqmp_clk_get_pll_rate: read (0xff5e0020), value (0x13200)
#sudo gdb --args /home/dkang/WORK/qemu-build-single/aarch64-softmmu/qemu-system-aarch64 -device loader,addr=0xfd1a0104,data=0x8000000e,data-len=4 -net nic -net nic -net nic -net nic,netdev=net0,macaddr=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device loader,addr=0x6000000,file=tmp/deploy/images/zcu102-zynqmp/core-image-minimal-zcu102-zynqmp-20170714142939.rootfs.cpio.gz.u-boot,force-raw=true -nographic -serial mon:stdio -serial null -hw-dtb DK/Single-Ref/zynqmp-qemu-arm.dtb -device loader,file=DK/bl31.elf,cpu-num=0 -device loader,file=DK/u-boot.2017.1.elf  -device loader,addr=0x4000000,file=DK/linux.dtb -device loader,addr=0x80000,file=DK/Image-test -machine arm-generic-fdt -m 4096 -D ./apu-test.log -d int,guest_errors,in_asm,fdt
